version: '3.9'

networks:
  app-tier:
    driver: bridge

services:
    mysql:
        image: bitnami/mysql:8.0-debian-11
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - app-tier
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql_data:/bitnami/mysql/data:Z

    phpfpm:
        build: 
          context: ./phpfpm
        networks:
            - app-tier
        volumes:
            - ./logs/symfony:/var/www/symfony/var/log:Z
        depends_on:
            - mysql

    nginx:
        build: 
            context: ./nginx
        networks:
            - app-tier
        ports:
            - "${NGINX_PORT}:80"
        depends_on:
            - phpfpm
        environment:
            - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
            - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
            - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
        volumes:
            - ./logs/nginx:/var/log/nginx:Z

    phpmyadmin:
        image: bitnami/phpmyadmin:5-debian-11
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - app-tier
        ports:
            - '${PMA_PORT}:8080'
            - '${PMA_PORT_SSL}:8443'
        restart: unless-stopped
        depends_on:
            - mysql

volumes:
  mysql_data:
    driver: local
  phpfpm_sock:
