<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBZm9NP5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBZm9NP5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBZm9NP5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBZm9NP5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBZm9NP5\App_KernelDevDebugContainer([
    'container.build_hash' => 'BZm9NP5',
    'container.build_id' => 'df8b41ce',
    'container.build_time' => 1673541380,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBZm9NP5');
