<?php

namespace ContainerBZm9NP5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4CdMfztService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4CdMfzt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4CdMfzt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'auteurRepository' => ['privates', 'App\\Repository\\AuteurRepository', 'getAuteurRepositoryService', true],
        ], [
            'auteurRepository' => 'App\\Repository\\AuteurRepository',
        ]);
    }
}
