<?php

namespace ContainerBZm9NP5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X48rnfUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X48rnfU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X48rnfU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AuteurController::delete' => ['privates', '.service_locator.9JvWJ.1', 'get_ServiceLocator_9JvWJ_1Service', true],
            'App\\Controller\\AuteurController::edit' => ['privates', '.service_locator.9JvWJ.1', 'get_ServiceLocator_9JvWJ_1Service', true],
            'App\\Controller\\AuteurController::index' => ['privates', '.service_locator.4CdMfzt', 'get_ServiceLocator_4CdMfztService', true],
            'App\\Controller\\AuteurController::show' => ['privates', '.service_locator.9JvWJ.1', 'get_ServiceLocator_9JvWJ_1Service', true],
            'App\\Controller\\BookController::delete' => ['privates', '.service_locator.VH_0EHf', 'get_ServiceLocator_VH0EHfService', true],
            'App\\Controller\\BookController::edit' => ['privates', '.service_locator.VH_0EHf', 'get_ServiceLocator_VH0EHfService', true],
            'App\\Controller\\BookController::index' => ['privates', '.service_locator.B2ZeSAD', 'get_ServiceLocator_B2ZeSADService', true],
            'App\\Controller\\BookController::show' => ['privates', '.service_locator.VH_0EHf', 'get_ServiceLocator_VH0EHfService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AuteurController:delete' => ['privates', '.service_locator.9JvWJ.1', 'get_ServiceLocator_9JvWJ_1Service', true],
            'App\\Controller\\AuteurController:edit' => ['privates', '.service_locator.9JvWJ.1', 'get_ServiceLocator_9JvWJ_1Service', true],
            'App\\Controller\\AuteurController:index' => ['privates', '.service_locator.4CdMfzt', 'get_ServiceLocator_4CdMfztService', true],
            'App\\Controller\\AuteurController:show' => ['privates', '.service_locator.9JvWJ.1', 'get_ServiceLocator_9JvWJ_1Service', true],
            'App\\Controller\\BookController:delete' => ['privates', '.service_locator.VH_0EHf', 'get_ServiceLocator_VH0EHfService', true],
            'App\\Controller\\BookController:edit' => ['privates', '.service_locator.VH_0EHf', 'get_ServiceLocator_VH0EHfService', true],
            'App\\Controller\\BookController:index' => ['privates', '.service_locator.B2ZeSAD', 'get_ServiceLocator_B2ZeSADService', true],
            'App\\Controller\\BookController:show' => ['privates', '.service_locator.VH_0EHf', 'get_ServiceLocator_VH0EHfService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AuteurController::delete' => '?',
            'App\\Controller\\AuteurController::edit' => '?',
            'App\\Controller\\AuteurController::index' => '?',
            'App\\Controller\\AuteurController::show' => '?',
            'App\\Controller\\BookController::delete' => '?',
            'App\\Controller\\BookController::edit' => '?',
            'App\\Controller\\BookController::index' => '?',
            'App\\Controller\\BookController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AuteurController:delete' => '?',
            'App\\Controller\\AuteurController:edit' => '?',
            'App\\Controller\\AuteurController:index' => '?',
            'App\\Controller\\AuteurController:show' => '?',
            'App\\Controller\\BookController:delete' => '?',
            'App\\Controller\\BookController:edit' => '?',
            'App\\Controller\\BookController:index' => '?',
            'App\\Controller\\BookController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
