<?php

namespace ContainerA42rPW4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZHncYHhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZHncYHh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZHncYHh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AuteurController::delete' => ['privates', '.service_locator.PsDS_hI', 'get_ServiceLocator_PsDSHIService', true],
            'App\\Controller\\AuteurController::edit' => ['privates', '.service_locator.PsDS_hI', 'get_ServiceLocator_PsDSHIService', true],
            'App\\Controller\\AuteurController::index' => ['privates', '.service_locator.dZK.biq', 'get_ServiceLocator_DZK_BiqService', true],
            'App\\Controller\\AuteurController::show' => ['privates', '.service_locator.PsDS_hI', 'get_ServiceLocator_PsDSHIService', true],
            'App\\Controller\\BookController::delete' => ['privates', '.service_locator.qkm.aLw', 'get_ServiceLocator_Qkm_ALwService', true],
            'App\\Controller\\BookController::edit' => ['privates', '.service_locator.qkm.aLw', 'get_ServiceLocator_Qkm_ALwService', true],
            'App\\Controller\\BookController::index' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'App\\Controller\\BookController::show' => ['privates', '.service_locator.qkm.aLw', 'get_ServiceLocator_Qkm_ALwService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\AuteurController:delete' => ['privates', '.service_locator.PsDS_hI', 'get_ServiceLocator_PsDSHIService', true],
            'App\\Controller\\AuteurController:edit' => ['privates', '.service_locator.PsDS_hI', 'get_ServiceLocator_PsDSHIService', true],
            'App\\Controller\\AuteurController:index' => ['privates', '.service_locator.dZK.biq', 'get_ServiceLocator_DZK_BiqService', true],
            'App\\Controller\\AuteurController:show' => ['privates', '.service_locator.PsDS_hI', 'get_ServiceLocator_PsDSHIService', true],
            'App\\Controller\\BookController:delete' => ['privates', '.service_locator.qkm.aLw', 'get_ServiceLocator_Qkm_ALwService', true],
            'App\\Controller\\BookController:edit' => ['privates', '.service_locator.qkm.aLw', 'get_ServiceLocator_Qkm_ALwService', true],
            'App\\Controller\\BookController:index' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'App\\Controller\\BookController:show' => ['privates', '.service_locator.qkm.aLw', 'get_ServiceLocator_Qkm_ALwService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\AuteurController::delete' => '?',
            'App\\Controller\\AuteurController::edit' => '?',
            'App\\Controller\\AuteurController::index' => '?',
            'App\\Controller\\AuteurController::show' => '?',
            'App\\Controller\\BookController::delete' => '?',
            'App\\Controller\\BookController::edit' => '?',
            'App\\Controller\\BookController::index' => '?',
            'App\\Controller\\BookController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AuteurController:delete' => '?',
            'App\\Controller\\AuteurController:edit' => '?',
            'App\\Controller\\AuteurController:index' => '?',
            'App\\Controller\\AuteurController:show' => '?',
            'App\\Controller\\BookController:delete' => '?',
            'App\\Controller\\BookController:edit' => '?',
            'App\\Controller\\BookController:index' => '?',
            'App\\Controller\\BookController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
